// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Musica;

namespace Musica.Migrations
{
    [DbContext(typeof(MusicaDbContext))]
    partial class MusicaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.14");

            modelBuilder.Entity("Musica.Artist", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("image_url")
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.Property<string>("url")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Artists");
                });

            modelBuilder.Entity("Musica.EmailToken", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdUser")
                        .HasColumnType("TEXT");

                    b.Property<string>("Token")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("EmailTokens");
                });

            modelBuilder.Entity("Musica.Song", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("artist_names")
                        .HasColumnType("TEXT");

                    b.Property<string>("full_title")
                        .HasColumnType("TEXT");

                    b.Property<string>("header_image_url")
                        .HasColumnType("TEXT");

                    b.Property<string>("recording_location")
                        .HasColumnType("TEXT");

                    b.Property<string>("release_date_for_display")
                        .HasColumnType("TEXT");

                    b.Property<string>("title")
                        .HasColumnType("TEXT");

                    b.Property<string>("url")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Songs");
                });

            modelBuilder.Entity("Musica.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Musica.UserArtist", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdArtist")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IdUser")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UsersArtists");
                });

            modelBuilder.Entity("Musica.UserSong", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdSong")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IdUser")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UsersSongs");
                });
#pragma warning restore 612, 618
        }
    }
}
